<?php

namespace AppBundle\Repository;

/**
 * Image
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Image extends \Doctrine\ORM\EntityRepository
{
}
